name: Android CI

on:
  push:
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          components: build-tools;34.0.0
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/build.gradle*','android/**/build.gradle.kts','android/gradle.properties','android/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Lint and unit tests
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: android
          arguments: lint test