name: ESP32 CI

on:
  push:
    paths:
      - 'esp32/**'
      - '.github/workflows/esp32.yml'
  pull_request:
    paths:
      - 'esp32/**'
      - '.github/workflows/esp32.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: esp32
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install -U platformio
      - name: Build firmware
        run: pio run